[package]
name = "ical_property"
version = "0.1.0"
edition = "2021"

description = "Get a struct with all properties from an ical calendar."

license = "MIT"

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
dateparser = "0.2.1"
ical = "0.11.0"
regex = "1.11.1"
rrule = "0.13.0"
